version: "3"

# $ docker run --name some-mariadb -e MYSQL_ROOT_PASSWORD=my-secret-pw -d mariadb:tag --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

services:
  mariadb:
    image: mariadb
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    environment:
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - 3306:3306
    volumes:
      - ./sql/:/docker-entrypoint-initdb.d/
    networks:
      - network

  adminer:
    image: adminer
    depends_on:
      - mariadb
    environment:
      ADMINER_DEFAULT_SERVER: mariadb
      ADMINER_DEFAULT_DB_DRIVER: mysql
      ADMINER_DEFAULT_DB_HOST: mariadb
    ports:
      - 8082:8080
    networks:
      - network

networks:
  network:
    driver: bridge
